[package]
name = "ics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
chrono-tz = "0.8.0"
time = "0.3.16"

[lib]
doc = true
name = "ics"
path = "src/lib.rs"
test = true
